### PR TITLE
fixed merge issues

### PR DESCRIPTION
**Pull request by Bookcliff**
Added an issuances section to list the past and current/upcoming issuances.

https://www.loom.com/share/7decc20a51844689b48d8e7a97959f4a

### CODE REVIEW

**Comment by RusseII** [comment]
Looks great! Should Past Issuances and Current and Upcoming be a smaller text size? 
CleanShot 2022-11-22 at 08 03 50@2x

**Comment by RusseII** [comment]
fixes https://github.com/alwaysbegrowing/company/issues/14

**Comment by Namaskar-1F64F** [comment]
when collapsed, the current & upcoming isn't full width
image

**Comment by Namaskar-1F64F** [comment]
the features accordion needs to have the `id="features"` added back. feature images do not change without it. 
image

**Comment by Bookcliff** [comment]
> when collapsed, the current & upcoming isn't full width image

Fixed

image

**Comment by Bookcliff** [comment]
> the features accordion needs to have the `id="features"` added back. feature images do not change without it. image

Fixed

image

**Comment by Bookcliff** [comment]
> Looks great! Should Past Issuances and Current and Upcoming be a smaller text size? CleanShot 2022-11-22 at 08 03 50@2x

Fixed

image

**Comment by Namaskar-1F64F** [comment]
lgtm!

**Pull request merged**
