### PR TITLE
Lighthouse

### PR DESCRIPTION
**Pull request by Bookcliff**
Improve lighthouse scores

Increased the performance, accessibility, best practices, and SEO scores. Not all of the recommendations could be completed due to them not making sense in the context of the webpage.

### CODE REVIEW

**Comment by Namaskar-1F64F** [comment]
looks good to me. when loading "mobile" score, the images say can be improved 
image
by what looks like a lot. I haven't heard of those "next gen" formats or if they work on all the devices, but changing those to the new format and hosting them locally (in the project vs imgur.com) might be a good idea. 

Also the fonts may be improved by adding `defer` but not sure on that.
image

**Comment by Bookcliff** [comment]
I added defer and am not seeing the render blocking issue anymore.

**Comment by Bookcliff** [comment]
Fixed images by adding .webp files for all imported images.

**Comment by Namaskar-1F64F** [comment]
Looks good. Mobile performance is still unhappy, but an improvement from before. there don't seem to be any other easy fixes like you said.

image
image

**Pull request merged**
